"""Make the bundled runtime relocatable.

The application ships its own GTK, X and VNC runtime under ``depends/``,
because TOS 7 provides no desktop libraries. Those libraries were built against
the absolute paths of the machine that produced them, so something has to point
them at the copy that actually shipped. That is this module's whole job.

Two kinds of relocation are needed:

* **Environment variables.** GTK, gdk-pixbuf, GIO and fontconfig all accept a
  variable that overrides where they look. Setting them is what upstream's own
  AppImage build does, through the linuxdeploy GTK plugin.

* **Rewritten cache files.** ``loaders.cache`` and ``immodules.cache`` are
  plain text whose every other line is an absolute path recorded at build time.
  No environment variable overrides those entries, so the files themselves are
  rewritten. This is done at startup rather than at install time so the bundle
  keeps working when it is run from an arbitrary staging directory during a
  diagnostic.

darktable itself needs none of this: it locates its own data through
``whereami`` and paths baked in relative to the executable, which is why its
tree lives untouched under ``app/``.
"""

import os
import posixpath
import re

from . import logging_setup

log = logging_setup.get_logger("bundle")

_QUOTED = re.compile(r'^(\s*)"(/[^"]*)"(\s*)$')

_FONTCONFIG_TEMPLATE = """<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- Generated by the darktable launcher at startup. Rewritten on every start
     so that the bundle stays relocatable; do not edit by hand, edit
     lib/bundle.py instead. -->
<fontconfig>
  <dir>{share}/fonts</dir>
  <cachedir>{cache}</cachedir>
</fontconfig>
"""


def write_fontconfig(config):
    """Write a fontconfig configuration pointing only inside the bundle.

    The system file lists ``/usr/share/fonts``, ``/usr/local/share/fonts`` and
    ``~/.fonts``. On a NAS root filesystem none of those exist, so GTK would
    find no font at all and every label would render as empty boxes. Shipping
    our own file with a private cache directory is what makes text appear.
    """
    path = config.fontconfig_file
    os.makedirs(os.path.dirname(path), exist_ok=True)
    content = _FONTCONFIG_TEMPLATE.format(
        share=config.depends_share, cache=config.fontconfig_cache
    )
    try:
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
    except OSError as error:
        log.error("cannot write %s: %s", path, error)
        return False
    return True


def rewrite_module_cache(path, module_dir):
    """Repoint an absolute-path cache file at the bundled module directory.

    The file alternates a quoted basename with metadata and a quoted absolute
    path. Rewriting by basename rather than by string substitution means the
    result is correct whatever directory the build host used, which is what
    keeps this working when the closure is collected on a different machine
    than the one that built darktable.

    Returns the number of entries rewritten, or -1 when the file is absent.
    """
    if not os.path.isfile(path):
        return -1

    try:
        with open(path, "r", encoding="utf-8") as handle:
            lines = handle.readlines()
    except OSError as error:
        log.warning("cannot read %s: %s", path, error)
        return -1

    rewritten = 0
    out = []
    for line in lines:
        match = _QUOTED.match(line.rstrip("\n"))
        if not match:
            out.append(line)
            continue
        indent, value, trailing = match.groups()
        if not value.startswith("/"):
            out.append(line)
            continue
        # posixpath, not os.path: the entries inside these cache files are
        # POSIX paths consumed by Linux code whichever platform performed the
        # rewrite. Building them with the host's separator would produce a file
        # that parses correctly here and not on the device.
        replacement = posixpath.join(module_dir, posixpath.basename(value))
        out.append('%s"%s"%s\n' % (indent, replacement, trailing))
        rewritten += 1

    if rewritten:
        try:
            with open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.writelines(out)
        except OSError as error:
            log.warning("cannot write %s: %s", path, error)
            return -1
    return rewritten


def prepare(config):
    """Do the filesystem half of relocation. Call once at startup."""
    write_fontconfig(config)

    for name, module_dir in (
        (
            "gdk-pixbuf-2.0/2.10.0/loaders.cache",
            "gdk-pixbuf-2.0/2.10.0/loaders",
        ),
        ("gtk-3.0/3.0.0/immodules.cache", "gtk-3.0/3.0.0/immodules"),
    ):
        cache_path = os.path.join(config.depends_lib, name)
        count = rewrite_module_cache(cache_path, os.path.join(config.depends_lib, module_dir))
        if count > 0:
            log.info("rewrote %d path(s) in %s", count, name)
        elif count == 0:
            log.warning("%s contained no absolute paths to rewrite", name)


def child_environment(config, display=None):
    """Return the environment for darktable and the X/VNC servers.

    Built from a copy of the current environment so that PATH and LANG survive,
    then overridden. Everything that could make a library reach for a host path
    is set explicitly.
    """
    env = dict(os.environ)

    lib_dirs = [config.depends_lib, os.path.join(config.app_dir, "lib", "darktable")]
    existing = env.get("LD_LIBRARY_PATH")
    if existing:
        lib_dirs.append(existing)
    env["LD_LIBRARY_PATH"] = ":".join(lib_dirs)

    env["PATH"] = os.pathsep.join(
        [config.depends_bin, os.path.join(config.app_dir, "bin"), env.get("PATH", "/usr/bin:/bin")]
    )

    # GTK and its friends.
    env["GTK_EXE_PREFIX"] = config.root
    env["GTK_DATA_PREFIX"] = config.root
    env["GTK_PATH"] = os.path.join(config.depends_lib, "gtk-3.0")
    env["GTK_IM_MODULE_FILE"] = os.path.join(
        config.depends_lib, "gtk-3.0", "3.0.0", "immodules.cache"
    )
    env["GDK_PIXBUF_MODULEDIR"] = os.path.join(
        config.depends_lib, "gdk-pixbuf-2.0", "2.10.0", "loaders"
    )
    env["GDK_PIXBUF_MODULE_FILE"] = os.path.join(
        config.depends_lib, "gdk-pixbuf-2.0", "2.10.0", "loaders.cache"
    )
    env["GSETTINGS_SCHEMA_DIR"] = os.path.join(config.depends_share, "glib-2.0", "schemas")
    env["GIO_EXTRA_MODULES"] = os.path.join(config.depends_lib, "gio", "modules")

    # There is no GPU driver on a NAS. Asking for X11 with GL disabled makes
    # GTK fall back to cairo software rendering, which is the only path that
    # works and avoids a long stall while GLX fails to initialise.
    env["GDK_BACKEND"] = "x11"
    env["GDK_GL"] = "disable"
    env["LIBGL_ALWAYS_SOFTWARE"] = "1"

    env["XDG_DATA_DIRS"] = os.pathsep.join([config.depends_share, "/usr/share"])
    env["XDG_CONFIG_DIRS"] = os.pathsep.join([config.depends_etc, "/etc"])

    env["FONTCONFIG_FILE"] = config.fontconfig_file
    env["FONTCONFIG_PATH"] = os.path.dirname(config.fontconfig_file)

    # Every write stays inside the application directory.
    env["HOME"] = config.home_dir
    env["XDG_CONFIG_HOME"] = os.path.join(config.home_dir, ".config")
    env["XDG_CACHE_HOME"] = os.path.join(config.home_dir, ".cache")
    env["XDG_DATA_HOME"] = os.path.join(config.home_dir, ".local", "share")
    env["XDG_RUNTIME_DIR"] = config.run_dir
    env["TMPDIR"] = config.tmp_dir

    # No accessibility bus and no session bus exist in a systemd service
    # without a login session; without this GTK logs a warning on every start
    # that looks like a fault and is not one.
    env["NO_AT_BRIDGE"] = "1"

    env["OMP_NUM_THREADS"] = str(config.dt_threads)
    env["OMP_DYNAMIC"] = "FALSE"

    if display is not None:
        env["DISPLAY"] = display
        env["XAUTHORITY"] = config.xauth_file

    return env


def missing_pieces(config):
    """Return the bundle files that are absent, for a loud startup failure.

    A missing gdk-pixbuf loader or schema compiles fine and fails only as a
    blank window, which is a slow thing to diagnose on a device. Checking up
    front turns that into one clear log line.
    """
    expected = [
        config.darktable_binary,
        config.xvfb_binary,
        config.x11vnc_binary,
    ]
    missing = [path for path in expected if not os.path.exists(path)]
    if not os.path.isdir(config.depends_lib):
        missing.append(config.depends_lib)
    return missing
